* KiteAB Emacs
  Hello everyone, this repository saved my personal emacs configuration file.

  You can find the Emacs Guides at [[https://github.com/KitPixel/emacs-guides][this repository]].

  * [[#dependencies][Dependencies]]
  * [[#installation][Installation]]
    - [[#update-site-lisp][Update Site Lisp]]
    - [[#add-more-site-lisp][Add More Site Lisp]]
  * [[#shortcuts][Shortcuts]]
  * [[#token][Token]]
  * [[#notes][Notes]]
  * [[#contributors][Contributors]]

** Dependencies
   You need some dependencies at below:
   - Emacs (Details like version and system is in [[#notes][Notes part]])
   - Git
   - libvterm (To use VTerm)
   - CMake (To compile the VTerm)
   - Fira Code Nerd Font (Optional. You can edit the font use ~C-q c lisp TAB config TAB init-ui.el RET~)
   - The dependencies in [[https://github.com/manateelazycat/emacs-application-framework][Emacs Application Framework]]. (To use EAF)
   - The dependencies in [[https://github.com/loyalpartner/english-teacher.el][English Teacher]]. (To use English Teacher)
   - ~ttf-symbola~ font. (Optional. Telega icons)

** Installation
   You need to clone this repository to your ~$HOME/kiteab-emacs~

   And install the [[#dependencies][dependencies]]

   Then, run command below:
   #+begin_src shell
   git submodule update --init --recursive
   #+end_src
   And see the [[#token][Token]] part to edit ~eaf-grip-token~

   Then enjoy the Emacs!

*** Update Site Lisp
    If you want to update the packages in ~site-lisp~ folder, you need to run command below:
    #+begin_src shell
    git submodule foreach git pull
    #+end_src
    #+begin_src shell
    git pull --recurse-submodules
    #+end_src
    Or:
    #+begin_src shell
    git submodule update --recursive
    #+end_src
    Info: The EAF package is pull from my [[https://gitee.com/KiteAB/emacs-application-framework][mirror repository]], and I will merge it with the [[https://github.com/manateelazycat/emacs-application-framework][original repository]] every week!

*** Add More Site Lisp
    If you want to add more site lisp, you can run commands below:
    #+begin_src shell
    git clone <repo link> site-lisp/<repo name>
    git submodule add <repo link> site-lisp/<repo name>
    #+end_src
    Then you can manage your third party packages by ~git submodule~!

** Shortcuts
*** Default
    I binded the ~C-q~ key to be the user defined key.

    ~C-q~ key bind the functions in ~site-lisp/config/init-functions.el~

    You can view this file and change somethings.

*** Xah Fly Keys
    I'm learning to use xah fly keys, and if you don't like it, you can go to ~site-lisp/config/init.el~ file and comment ~(require 'init-xah-fly-keys)~ use ~;;~.

** Token
   You need to do the following to make markdown/org preview work properly:
   - ~touch ~/.emacs.d/site-lisp/config/init-eaf.el~
   - Edit the ~init-eaf.el~ file and edit somethings below:
   #+begin_src emacs-lisp
     (setq eaf-grip-token "token")
   #+end_src
   And go to the [[https://github.com/settings/tokens/new?scopes=][GitHub Personal Access Token Site]] to create your personal token.

   Then replace ~token~ to your personal token.

** Notes
   - This configuration file is best run on GNU/Linux Emacs 27.1, Windows may have some problems such as [[https://github.com/KiteAB/.emacs.d/issues/1][this issue]].
   - Emacs can't search and autoload ~site-start.el~, so you need create an ~.emacs~ file in your home directory and write them in:
     #+begin_src emacs-lisp
       (load-file "path/to/site-start.el")
     #+end_src

** Contributors
   - *[[https://github.com/KiteAB][David Zhang]]*: The original creator of this repository.
   - *[[https://github.com/JimMoen][JimMoen]]*: Cleaned up and improved the codes, see [[https://github.com/KiteAB/.emacs.d/pull/1][#1]] for details.
   - *[[https://github.com/SpringHan][SpringHan]]*: Codes part provided.
   - *[[https://github.com/EvanMeek][EvanMeek]]*: Codes part provided.
   - *[[https://github.com/manateelazycat][Andy Stewart]]*: Multiple packages and codes part provided.
   - *[[https://github.com/redguardtoo][Chen Bin]]*: Encouragement and support provided.
   - *[[https://github.com/vritser][Vritser]]*: Improved the codes, see [[https://github.com/KiteAB/.emacs.d/pull/5][#5]]
